openshift/sandboxed-containers-operator

- deploy/operator.yaml
Point image to isolatedcontainers/kata-operator-payload in quay.io
> fix image in operator.yaml

- version/version.go
> Add version 4.6.0

- config/manager/manager.yaml
Signed-off-by: Harshal Patil <harpatil@redhat.com>
> schedule controller only on master nodes

- pkg/controller/kataconfig/openshift_reconciler.go
In some compact clusters variants nodes have both the master and worker
role.  However, the machine config pools that are used in
these configurations have all nodes in the master pool and zero nodes in
the worker pool.
Zero nodes in the worker pool breaks our current practice of installing
kata on all nodes in the worker pool. The solution is to install on all
nodes in the master pool instead. For that we fetch the worker pool
information and check if it has nodes in it. If it has a machine count
of zero we use the master pool instead.
This has an important implication:
in this master-only configuration we can't support installing on a
subset of nodes by setting a label on the selected nodes the user wants
to install kata on. Why? This feature depends on creating a custom pool
that …
> add support for master/worker combined nodes

- README.md
We want to make sure people use the branch we have tested
> Add hint to release-4.6 in README

- README.md
replace private build with quay.io/isolatedcontainers/kata-operator:4.7
> use official container image in README

- controllers/openshift_controller_test.go
- controllers/suite_test.go
This reverts commit abcec60996ecc8fe6ff5b4e6a1eb0d480eb8672f.
Remove a broken test that was pushed in a different PR by accident
> Revert "add test for installation"

- docs/DEVELOPMENT.md
The example yaml was not formatted correctly and was hard to read.
Add backticks around the example for inline code formatting
n/a
n/a
> format example yaml correctly

- README.md
**-What I did**
Rename all occurrences of the github repo name. Basically s/openshift\/kata-operator/sandboxed-containers/operator/g
Read the document and search for typos or missed renames
Use new repository name in README.md
> Update README.md to use new repository name

- docs/DEVELOPMENT.md
The name of the repository was changed. Let's use the new name in the
developers documentation as well.
Change one occurence of the old name.
Read the document make sure I didn't miss anything
Updated Development.md to use new repository name
> Update DEVELOPMENT.md, use new repository name

- images/daemon/pkg/daemon/kata_openshift.go
This PR adds support for installing Kata 2.x
Updated daemon code to use kata-containers package
By checking the kata-containers rpm version in the worker node
Add support for Kata containers version 2.x
> Add support for kata-2.x

- .travis.yml
- ISSUE_TEMPLATE.md
- Makefile
- PROJECT
- README.md
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/rbac/auth_proxy_service.yaml
- config/samples/catalogsource.yaml
- config/samples/configmap_payload.yaml
- controllers/kataconfig_controller.go
- controllers/kubernetes_controller.go
- controllers/openshift_controller.go
- controllers/openshift_controller_test.go
- controllers/suite_test.go
- deploy/deploy.sh
- deploy/deploy.yaml
- deploy/install.sh
- docs/DEVELOPMENT.md
- go.mod
- main.go
Rename kata-operator to sandboxed-containers-operator
Renamed kata-operator to sandboxed-containers-operator and bumped up the version to 4.8
Renamed the namespace to sandboxed-containers-operator-system
Deploy the operator by following the instructions
Rename kata-operator to sandboxed-containers-operator
> Rename operator to sandboxed-containers-operator

- controllers/openshift_controller.go
Increment the completedNotesCount field in kataconfig during
install/uninstall.
- Description of the problem which is fixed/What is the use case
Other than in 4.7 with the 4.8 operator we don't update the completedNodesCount field
in kataconfig anymore. A regression introduced when we removed the daemon.
- What I did
Add code to update the field during install/uninstall.
- How to verify it
Install/uninstall and watch the value being set as nodes are completed
- Description for the changelog
Fix regression that led to the updatedNodesCount field not being updated
> [backport] use completedNodesCount field

- bundle.Dockerfile
- bundle/manifests/kata-operator.clusterserviceversion.yaml
- bundle/manifests/sandboxed-containers-operator.crd.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/extension-crds/machineconfig.crd.yaml
- config/extension-crds/machineconfigpool.crd.yaml
- controllers/openshift_controller.go
- controllers/suite_test.go
Backport fixes from main branch
> Backports for release-4.8 branch

- Makefile
- controllers/openshift_controller_test.go
This patch adds new unit tests to improve code coverage from ~10% to ~48%
Consequently the test execution time increases.
Added few additional unit tests.
make test
Add new unit tests to improve code coverage
> Add new unit tests to improve code coverage

- must-gather/collection-scripts/gather_sandboxed_containers_logs
Please comment on paths, filenames, sanity checks, completeness etc.  I'm submitting this PR mostly to get early feedback rather than to claim this is ready to be merged!
> add operator-related data to must-gather collection

- Dockerfile
- controllers/openshift_controller_test.go
- controllers/suite_test.go
With addition of webhook, the related unit tests need to be fixed to handle the same
Updated the code to install webhook in envtest and modify the test cases
`make test` 
Fix unit tests to handle webhook
> Fix unit tests to handle webhook

- Dockerfile
- Makefile
- bundle.Dockerfile
- bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
- bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
- config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
> operator-sdk upgrade and Dockerfile update

- README.md
The README was dated containing incorrect installation instructions.
Fixes: #156, #157 , #158 , #159 
Added instructions to deploy 1.1 on OpenShift 4.9
By following the instructions to deploy the operator
Fix deployment instructions for release-1.1 on OCP4.9
> Update README for 1.1 release

- README.md
The install instructions were incorrect
Partially Fixes: #156 
Updated with correct install instructions
Install the operator by following the instructions in the README
Fix install instruction.
> Update deployment instructions for OCP 4.8

- main.go
This patches an existing SCC so that it no longer breaks MCO, i.e. applying
the same changes as described in MR #196. This will allow seamless upgrade
of OCP (extra manual steps are required otherwise).
> Fix 1.2-style SCC

- bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
OCP 4.12 is now enforcing the "restricted" Pod Security Admission (PSA) policy by default for every pod. This includes the pods that belong to the operator, i.e. the controller manager and the monitors. As a consequence, subscribing to OSC currently fails with the following error:
message: 'pods "controller-manager-6dff96dbb8-m2twk" is forbidden: violates
PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container
"manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted
capabilities (container "manager" must set securityContext.capabilities.drop=["ALL"]),
runAsNonRoot != true (pod or container "manager" must set securityContext.runAsNonRoot=true),
seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type
to …
> Add security contexts to the operator (1.3 backport)

- config/crd/bases/confidentialcontainers.org_peerpodconfigs.yaml
to match what peer-pod-controller has
> add configMapName to peerpodconfig crd

- config/peerpods/webhook-deploy.yaml
change similar to but adapted to openshift namespaces (list provided by @bpradipt)
> webhook: Ensure webhook gets called for pods created in all user namespaces

- config/peerpods/peerpodscm.yaml
- config/peerpods/peerpodssecret.yaml
Related-to: https://github.com/confidential-containers/cloud-api-adaptor/pull/465
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>
> dev-preview: peerpods: comment out sample config

- .gitignore
- Dockerfile
- docs/DEVELOPMENT.md
- go.mod
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
> Fix operator image build.

- podvm/Dockerfile.podvm
- podvm/Dockerfile.podvm.centos
- podvm/Dockerfile.podvm.rhel
- podvm/Dockerfile.podvm_builder
- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
- podvm/Makefile
- podvm/Makefile.inc
- podvm/files/etc/agent-config.toml
- podvm/files/etc/containers/policy.json
- podvm/files/etc/systemd/system/agent-protocol-forwarder.service
- podvm/files/etc/systemd/system/kata-agent.service
- podvm/files/etc/systemd/system/multi-user.target.wants/agent-protocol-forwarder.service
- podvm/files/etc/systemd/system/multi-user.target.wants/kata-agent.service
- podvm/files/etc/systemd/system/multi-user.target.wants/run-image.mount
- podvm/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers.mount
- podvm/files/etc/systemd/system/run-image.mount
- podvm/files/etc/systemd/system/run-kata\x2dcontainers.mount
- podvm/go.mod
- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/centos/variables.pkr.hcl
- podvm/qcow2/copy-files.sh
- podvm/qcow2/misc-settings.sh
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- podvm/qcow2/rhel/variables.pkr.hcl
- podvm/qcow2/selinux_relabel.sh
- podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- podvm/qcow2/ubuntu/variables.pkr.hcl
- podvm/qcow2/userdata.cfg
from https://github.com/confidential-containers/cloud-api-adaptor
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>
having the empty go.mod file is wanted or should be removed?
> adding podvm folder

- Makefile
> Makefile: update VERSION to 1.3.4

- podvm/Dockerfile.podvm
- podvm/Dockerfile.podvm.centos
- podvm/Dockerfile.podvm.rhel
- podvm/Dockerfile.podvm_builder
- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
- podvm/raw-to-ami.sh
- podvm/vmdk-to-ovf.sh
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>
> podvm: sync files with upstream repo

- controllers/openshift_controller.go
```
Instead of letting the user manually do the following: 
oc create secret generic auth-json-secret --from-literal=auth.json=\ 
$(oc get -n openshift-config secret/pull-secret -ojson | jq -r '.data.".dockerconfigjson" | @base64d') \
-n openshift-sandboxed-containers-operator
do the same programmatically in enablePeerPods().
Fixes: KATA-1998
```
> controller: automatically create a Secret containing the cluster's pull-secret

- Dockerfile
- Makefile
- api/v1/kataconfig_types.go
- controllers/openshift_controller.go
- docs/DEVELOPMENT.md
The main goal is to bring the valuable changes of #291 to the feature branch for upcoming v1.4.0. Merging was chosen over rebasing because it is way simpler in terms of amount of conflicts to handle (especially in go.mod).
```
git clone https://github.com/openshift/sandboxed-containers-operator.git
cd sandboxed-containers-operator/
git checkout -b merge-from-main origin/peer-pods-tech-preview 
git merge main
```
Run all tests
Only two conflicts in `controllers/openshift_controller.go` :
- addition of the extension_mc_name const
- "IsInProgress = corev1.ConditionFalse" fix
> Merge main into peer-pods-tech-preview

- controllers/openshift_controller.go
This a follow-up fix for PR #300 and [KATA-2139](https://issues.redhat.com//browse/KATA-2139), please see the commit message for details.
> Fix kataconfig deletion when no kata nodes are on cluster

- hack/azure-CVM-image-create-job.yaml
- hack/azure-CVM-image-delete-job.yaml
and a job for deletion of this image
the following variables needs to be set in peer-pods-cm/peer-pods-secret before execution:
AZURE_REGION
AZURE_TENANT_ID
AZURE_RESOURCE_GROUP
AZURE_SUBSCRIPTION_ID
AZURE_CLIENT_SECRET
AZURE_CLIENT_ID
* This also requires the subscription be enrolled in accessing RHEL 9.2 Azure image (rhel-cvm-test-preview 9_2)
> image-job: job for creation Azure CVM podvm image

- must-gather/must-gather-requirements.md
This is a followup to #365 that just fixes trivial formatting nits in the must-gather documentation.
> Fix md formatting

- Makefile
- config/manager/kustomization.yaml
- config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
- config/samples/deploy.yaml
- hack/aws-image-job.yaml
- hack/azure-image-job.yaml
> Bump version to 1.7.0

- go.mod
- go.sum
https://issues.redhat.com/browse/KATA-2857
Update peerpod controllers to v0.8.0-alpha.1
> Update peerpod controllers to v0.8.0-alpha.1

- Makefile
- config/manager/kustomization.yaml
- config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
- config/samples/deploy.yaml
- hack/aws-image-job.yaml
- hack/azure-image-job.yaml
This is to bring to the devel branch #386 that was done on the main branch.
EDIT: The PR's branch is indeed 45 commits away from devel but all these commits already exist in devel and git merge will do FF.
> Merge 1.5.3 to devel

- config/manager/manager.yaml
- config/peerpods/podvm/aws-VM-image-create-job.yaml
- config/peerpods/podvm/azure-VM-image-create-job.yaml
> Fix the podvm-payload image references
