pkg/controller/kataconfig/openshift_reconciler.go

Add a preStop handler to delete temporary directories the daemonset
creates during installation. This will help when the pods are deleted
during an ongoing installation.

daemonset: add preStop handler to clean up

---

deploy/operator.yaml
pkg/controller/kataconfig/openshift_reconciler.go

Use latest daemon image which has support to check the OCP version and choose the correct payload image. 
Fixes #2

use latest daemon image 

---

pkg/controller/kataconfig/openshift_reconciler.go
pkg/controller/kataconfig/openshift_reconciler_test.go

Do not allow controller to process multiple KataConfig CRs. 
Signed-off-by: Harshal Patil <harpatil@redhat.com>

Prevent multiple KataConfig CRs

---

README.md
deploy/deploy-k8s.sh
deploy/deploy.sh

When branching off the release-4.6 we did not change all the references to the master branch in the deployment scripts and yaml files. This PR fixes that.

Use files from release 4.6

---

pkg/controller/kataconfig/openshift_reconciler.go

The preStop hook command is not run in a chroot environment, so we
need to delete /host/<dir> instead of just /<dir>

add /host prefix to directories to be cleaned up

---

deploy/configmap_payload.yaml
docs/DEVELOPMENT.md
images/daemon/pkg/daemon/kata_openshift.go
images/payload/Dockerfile.custom
pkg/controller/kataconfig/openshift_reconciler.go

Sometimes we need to test new builds of RPMs, for example to
verify a bug in QEMU, kata-runtime or other packages.
For this purpose the user can now add a configmap with a single data
entry that specifies a URL to a container image, e.g.
quay.io/someuser/repository:tag.
The ConfigMap will be added to the Pod spec of the installer daemon pods as an
environment variable. If the variable is set the daemon will use it. If
not the default mechanism for choosing the payload image is used.
The purpose of this feature is for development purposes only. When the
ConfigMap is used the operator will print a warning that using
self-built RPMs taints the kataconfig installation.
Also add a description in docs/HACKING.md on how to use the ConfigMap
and how to build a custom payload image.
Signed-off-by: …

openshift: allow custom payload images for development

---

controllers/openshift_controller.go

Add /host to directories in rm command because it is not run in chroot
environment.
Fixes: #24 

fix command run at preStop event

---

README.md
config/samples/example-fedora.yaml

We've switched to 'kata' as runtimeclass because it is what upstream 
kata-deploy uses as well and users got confused about the -oc.
The changes is already in the release-4.6 branch but on the master branch
we are still missing this change. 
Fix the example pod file accordingly.

Fix example fedora yaml runtimeclass

---

Makefile
controllers/openshift_controller.go

When code for the new operator was merged first we missed that
there is still a private test container image referenced in the
code.
This patch fixes it and changes the container image to
quay.io/isolatedcontainers/kata-operator-daemon:4.7

change kata-operator-daemon container image

---

README.md

To make it more clear I change the column "Repository" to "Container repository" and also add a sentence in the description as to where the Dockerfile can be found. 
Also fix the URls from github.com to quay.io.

Fix description and URLs of containers in README

---

README.md

There is no release-4.7 branch as of today. Change the README to mention master branch instead.

fix README, change release-4.7 to master branch

---

controllers/openshift_controller.go

Upstream kata-deploy has the overhead of a Kata Pod
set as
overhead:
podFixed:
memory: "160Mi"
cpu: "250m"
(https://github.com/kata-containers/packaging/blob/master/kata-deploy/k8s-1.18/kata-runtimeClasses.yaml#L7)
So far we had no Pod Overhead set at all. Let's use the same values
as upstream uses to take the Pod resource overhead into account when the
'kata' runtime class is used.
Tested by checking for Overhead in runtimeclass yaml after it is created and found:
Overhead:                                                                                                                                                                                                                                      
Pod Fixed: …

runtimeclass: set pod overhead 

---

config/samples/configmap_payload.yaml
controllers/openshift_controller.go
docs/DEVELOPMENT.md
images/daemon/pkg/daemon/kata_openshift.go

Sometimes we need to test new builds of RPMs, for example to
verify a bug in QEMU, kata-runtime or other packages.
For this purpose the user can now add a configmap with a single data
entry that specifies a URL to a container image, e.g.
quay.io/someuser/repository:tag.
The ConfigMap will be added to the Pod spec of the installer daemon pods as an
environment variable. If the variable is set the daemon will use it. If
not the default mechanism for choosing the payload image is used.
The purpose of this feature is for development purposes only. When the
ConfigMap is used the operator will print a warning that using
self-built RPMs taints the kataconfig installation.
Also add a description in …

Custom payload images

---

config/samples/catalogsource.yaml

This example catalogsource can be applied to an OpenShift cluster to be
able to install the operator via the web console.
This example catalogsource can be applied to an OpenShift cluster to be
able to install the operator via the web console.
oc apply -f config/samples/catalogsource.yaml
Go to web console and try to install via Operatorhub
Added an example for a working catalogsource that can be used for installing the Operator via the web console

add example catalogsource

---

config/manager/manager.yaml

On OCP 4.7 clusters we have repeatedly seen the operator pod run into
OOM errors. The manager container is usually using around 40M and the limit was
30M.
This patch increases the memory limit for the manager container in
the pod to 60M and the request value to 45M.
Install Kata with the operator and uninstall, let it run for half an hour. There should be no restarts
of the operator pod and no OOM errors.
Increase memory limit and requests values for the manager container to limit 60M and request 45M

increase memory limits and requests for manager container

---

config/default/manager_auth_proxy_patch.yaml
controllers/openshift_controller.go

In disconnected environments container images are mirrored to a local
system. A imageContentSourcePolicy resource needs to be created that
points to the mirrored image. Since OCP 4.3 the default behaviour of
ICSP is mirror-by-digest-only.
For ease of use in disconnected environment this patch switches the
references to container images in the operator code to use digests
instead of tags.
This patch is not changing the daemon to download the payload image via
digests on purpose. For disconnected environments the configmap for
payloads can be used.
Verify that the images used during installation - manager, kube-rbac-proxy 
and kata-operator-daemon - show up with @sha256:<somehash> in …

use digests for kube-rbac-proxy and kata-operator-daemon images

---

controllers/openshift_controller.go
controllers/openshift_controller_test.go
controllers/suite_test.go

In some compact clusters variants nodes have both the master and worker
role.  However, the machine config pools that are used in these
configurations have all nodes in the master pool and zero nodes in the
worker pool.
Zero nodes in the worker pool breaks our current practice of installing
kata on all nodes in the worker pool. The solution is to install on all
nodes in the master pool instead. For that we fetch the worker pool
information and check if it has nodes in it. If it has a machine count
of zero we use the master pool instead.
This has an important implication: in this master-only configuration we
can't support installing on a subset of nodes by setting a label on the
selected nodes the user …

forward-port from release-4.6: add support for master/worker combined nodes

---

controllers/openshift_controller.go
docs/DEVELOPMENT.md
images/daemon/pkg/daemon/kata_openshift.go

When a payload image is stored in a private repository the daemon
needs to authenticate with the registry to be able to download it.
Two sets of changes, one in the controller the other one in the daemon.
controller:
>When using a private repository for the payload image the
>daemon can now use the authentification credentials from a
>Kubernetes secret that is provided by the user.
>     
>This patch adds two environment variables for username and password
>to the daemon pod specification. The values are taken from a
>secret that the user needs to create before the pods are created.
>The environment variables are declared as optional so that no error
>occurs without the secret.
>
daemon:
>When a payload …

Daemon authenticate for payload image download

---

config/manager/manager.yaml

I've seen it several times that although a new image was pushed it wasn't
used on my cluster when it had been pulled down in a previous attempt already.
We want to make sure that the latest controller image is used,
so have the image always pulled down by setting ImagePullPolicy to always.
Test installing/uninstalling twice in a row with updating the image in between. If the description
of the controller pod says "image has already been pulled" it doesn't work.
Always pull down latest container image of the controller

set imagePullPolicy to Always for controller container

---

Makefile

On the second push to a repository in quay.io all images are converted
to schema v1. 
To work around this bug we build the container image
with --no-cache --squash-all
Run 'make docker-build IMG=' and push it. Then push it again. Inspect the image
with 'skopeo inspect' and verify it is still in schema v2 format.
Make sure container image is stored in schema v2 format.

make sure images are pushed as schema v2

---

README.md
deploy/deploy.sh
deploy/deploy.yaml
deploy/install.sh

This makes it simpler for users to deploy the operator. Users
won't need a checkout of the github repo.
Add a shell script  and deployment.yaml file in a new directory /deploy. 
The script takes care of creating all ressources by applying deploy/deploy.yaml,
adjusting the priviledges of the service account, etc. and it also creates a custom ressource.
It deploys the operator and creating a custom ressource.
Changed README.md to reflect these changes.
Follow the new instructions in README.md and install kata this way.
Simplified deployment, no checkout necessary any more

add deploy.sh for simpler deployment

---

controllers/openshift_controller.go

`privileged_without_host_devices` is an option from CRI-O configuration
files that controls whether the runtime handler will prevent host
devices from being passed to privileged containers.  Its default value
is `false` and we're switching it to `true` in order to avoid exposing
the host's `/dev`.
Enforced `privileged_without host_devices = true` for our installation.
When using `privileged: true`, check the content of `/dev` in the container.
Prevent host devices from being passed to privileged containers
**- Notes**
@bpradipt, @dgibson, I'm not exactly sure how it'd break (or not) SR-IOV and would be really nice if you guys could give it a try. …

controllers: Prevent host devices from being passed to privileged containers

---

images/daemon/go.mod
images/daemon/go.sum
images/daemon/pkg/daemon/kata_actions.go

Fixes #68
Fixes failed uninstall of Kata runtime when Kata is installed on specific nodes
Used fqdn for nodename instead of host name
Build the kata-operator-daemon and push the image to registry. Thereafter modify kata-operator to use the kata-operator-daemon image and go through the install/uninstall cycle
Use FQDN for nodename

Use fqdn for node names

---

controllers/openshift_controller.go

Current Pod overhead memory is set to 160Mi.
Creating a simple Pod with and without the kata runtimeClass will show an accounted memory difference of 300Mi in the OpenShift console. As the memory usage due to the VM operations is dynamic and may easily increase (e.g., for fs caching) a sane value for the Pod overhead memory should be a bit more than that:  let's set it to 350Mi.

Pod Overhead: increase memory to 350Mi

---

controllers/openshift_controller.go

`kata-osbuilder-generate.service` should be part of the RHCOS preset,
making it "enabled" by default whenever it's present / installed.
With that in mind, we can remove this logic from the operator and rely
on the OS to do the right thing for us.
Please, for more information about the work done on RHCOS side, refer
to: https://bugzilla.redhat.com/show_bug.cgi?id=1941342
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

controller: The service should be enabled by the OS

---

controllers/openshift_controller.go

Instead of having the logic of the CRI-O drop-in file in the operator,
let's just rely on it being distributed by the `kata-containers` RPM.
This is done because that file only makes sense in a system where
`kata-containers` RPM is installed, because that file is only used in a
system where `kata-containers` RPM is installed.  So, leave it for the
RPM to take care of that and let's make our lives simpler on the
operator side.

controller: The CRI-O drop-in file should be provided by the RPM

---

controllers/openshift_controller.go

This was removed by accident and missed in code review for pr #81. Let's put it
back and also change the namespace name to our default one. 

machine-config needs a name

---

controllers/openshift_controller.go

Increment the completedNotesCount field in kataconfig during
install/uninstall.
Other than in 4.7 with the 4.8 operator we don't update the completedNodesCount field
in kataconfig anymore. A regression introduced when we removed the daemon.
Add code to update the field during install/uninstall.
Install/uninstall and watch the value being set as nodes are completed
Fix regression that led to the updatedNodesCount field not being updated

use completedNodesCount field

---

Makefile
README.md

Although the subject line may be confused, we should aim for fully using
podman or docker, consistently. :-)
In order to do so, let's go for "docker" rather than "podman" and do the
switch of `make docker-push` to do a `podman push` rather than `docker
push`.
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

Makefile: `make docker-push` should use podman

---

controllers/openshift_controller.go

`kata-osbuilder-generate.service` should be part of the RHCOS preset,
making it "enabled" by default whenever it's present / installed.
With that in mind, we can remove this logic from the operator and rely
on the OS to do the right thing for us.
Please, for more information about the work done on RHCOS side, refer
to: https://bugzilla.redhat.com/show_bug.cgi?id=1941342
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

[backport] controller: The service should ne enabled by the OS

---

api/v1/kataconfig_types.go
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
controllers/openshift_controller.go

If user requests uninstallation of Kata by deleting their KataConfig
instance, the request cannot be fulfilled if there still are pods that use
Kata as runtime.  So far, the controller logged a message on detecting this
condition but since the message went to the controller log it wasn't very
well visible or discoverable.
This change creates a new field in KataConfig status to communicate the
error to the user more effectively.

inform user if kata uninstallation is blocked by existing kata-based pods

---

controllers/openshift_controller.go

We had two functions that were spelled almost the same and we removed
the wrong one. 
This commit is renaming the remaining function
to make it compile again.
make docker-build
Fix compilation error introduced when we removed one of two functions that were spelled almost the same

fix function name spelling of clearUninstallStatus

---

controllers/openshift_controller.go

We had two functions that were spelled almost the same and we removed
the wrong one. 
This commit is renaming the remaining function
to make it compile again.
make docker-build
Fix compilation error introduced when we removed one of two functions that were spelled almost the same

Fix build error misspelled function name 

---

Makefile
README.md
config/default/kustomization.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/samples/catalogsource.yaml
config/samples/configmap_payload.yaml
controllers/openshift_controller.go
deploy/deploy.sh
deploy/deploy.yaml

- use new namespace name and refer to new quay.io repository
We should adhere to the naming convention in OpenShift and use
the default namespace openshift-sandboxed-containers. The same goes for
the quay.io user/repository we use. Use the new
quay.io/openshift_sandboxed_containers instead of
quay.io/isolatedcontainres.
- delete example configmap for payload. We don't have a payload any more.
This cleans up README and example files to use the namespace
openshift-sandboxed-containers instead of sandboxed-containers-operator-system.
Follow the README descripton to install/uninstall and make sure all steps work.
Use new namespace …

Clean up and renames

---

Makefile
README.md
config/default/kustomization.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/samples/catalogsource.yaml
config/samples/configmap_payload.yaml
controllers/openshift_controller.go
deploy/deploy.sh
deploy/deploy.yaml

- Description of the problem which is fixed/What is the use case
use new namespace name and refer to new quay.io repository
We should adhere to the naming convention in OpenShift and use
the default namespace openshift-sandboxed-containers. The same goes for
the quay.io user/repository we use. Use the new
quay.io/openshift_sandboxed_containers instead of
quay.io/isolatedcontainres.
delete example configmap for payload. We don't have a payload any more.
- What I did
This cleans up README and example files to use the namespace
openshift-sandboxed-containers instead of sandboxed-containers-operator-system.
- How to verify it
Follow the README descripton to install/uninstall and make sure all steps work.
- Description for the changelog
Use new namespace openshift-sandboxed-containers and …

Clean up and renames 4.8

---

deploy/install.sh

Right now it uses files from the master branch. This is wrong, we always want to use the files from the release-4.7 branch.

Update install.sh, use files from release-4.7 branch

---

README.md

Right now it uses files from the master branch. This is wrong, we always want to use the files from the release-4.7 branch.

Update README.md to use files from release-4.7 branch

---

deploy/deploy.yaml

the repo name of the operator is wrong
use the correct name
Deploy the operator via oc apply -f deploy/deploy.yaml and check the image field in the pod spec of the controller
Fix deploy.yaml to use correct operator repository name

deploy.yaml: Fix operator repo name

---

bundle.Dockerfile

To enable the OpenShift CI to build the bundle image and test
installation of an Operator we need to add the Dockerfile to build
the bundle container image.
This was generated with 'make bundle'

add bundle.Dockerfile

---

bundle/manifests/kata-operator.clusterserviceversion.yaml
bundle/manifests/sandboxed-containers-operator.crd.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml

Openshift CI is able to build the operator bundle and index image and
test installation via OLM. For that it needs the files like the
clusterserviceversion, the crd and other metadata.
This patch adds these files which are a copy of the downstream product
version.

add bundle data

---

config/extension-crds/machineconfig.crd.yaml
config/extension-crds/machineconfigpool.crd.yaml
controllers/openshift_controller.go
controllers/suite_test.go

Output of kataconfig CR does not update when nodes are scaled up
Watch for changes to MachineConfigPool and trigger reconcile 
Add a new node to the existing cluster. Run `oc describe kataconfig example-kataconfig` to display the status of 
the CR
Update kataconfig CR status on scaling of nodes

Update kataconfig CR status on scaling of nodes

---

README.md
deploy/install.sh

When branching off from master we haven't changed all occurences of
the master branch name to release-4.8. Fix the README and helper
scripts in deploy/ to use the correct branch.
Fixes: #109

update README and deploy scripts to use release-4.8 branch

---

controllers/openshift_controller.go

Fix handling of custom MachineConfigPool
Closes: #107 
Made changes to the code to handle `kata-oc` MCP which is the custom MCP created by the operator.
Create a custom_kataconfig.yaml with the following content
```
apiVersion: kataconfiguration.openshift.io/v1
kind: KataConfig
metadata:
name: custom-kataconfig
spec:
kataConfigPoolSelector:
matchLabels:
custom-kata1: test
```
Label the worker nodes (eg worker0, worker1 in my setup)
$ oc label node worker0.ocp4.example.com custom-kata1=test
$ oc create -f custom_kataconfig.yaml
Once install succeeds, label the other worker
$ oc label node worker1.ocp4.example.com custom-kata1=test
Kataconfig CR should show updated status with new …

Fix handling of custom MachineConfigPool

---

README.md

Users shouldn't check out the master branch but the release-4.7 branch. Fix this in the README. 
Fixes: #113

Fix instructions in 'with git checkout' section

---

controllers/openshift_controller.go

Fixes: #118
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
Using MatchExpressions in KataConfigPoolSelector resulted in empty NodeSelector in RuntimeClass.
This is because RuntimeClass expects only MatchLabels and not MatchExpressions and Operator only
handled MatchLabels
Set the NodeSelector properly irrespective of using MatchLabels or MatchExpressions in KataConfigPoolSelector
Create KataConfig from OpenShift UI or use the following yaml
```
apiVersion: kataconfiguration.openshift.io/v1
kind: KataConfig
metadata:
name: example-kataconfig
spec:
kataConfigPoolSelector:
matchExpressions:
- key: custom-kata1
operator: In
values:
- "test"
```
**- Description for the …

Set NodeSelector correctly when using MatchExpressions in KataConfigPoolSelector

---

must-gather/Dockerfile
must-gather/LICENSE
must-gather/Makefile
must-gather/README.md
must-gather/collection-scripts/gather
must-gather/collection-scripts/gather_apiservices
must-gather/collection-scripts/gather_audit_logs
must-gather/collection-scripts/gather_crds
must-gather/collection-scripts/gather_images
must-gather/collection-scripts/gather_nodes
must-gather/collection-scripts/gather_sandboxed_containers_logs
must-gather/node-gather/node-gather-crd.yaml
must-gather/node-gather/node-gather-ds.yaml

While not strictly belonging to the Operator code, the team decided it's most practical
to maintain the must-gather scripts and relevant files in the same repository. 
must-gather is a tool built on top of OpenShift must-gather that expands
its capabilities to gather sandboxed containers information.
oc adm must-gather --image=quay.io/openshift_sandboxed_containers/openshift-sandboxed-containers-must-gather
The command above will create a local directory with a dump of the
OpenShift sandboxed-containers state. Note that this command will only
get data related to the sandboxed-containers part of the OpenShift
cluster.
You will get a dump of:
All namespaces (and their children objects) that belong to any
sandboxed …

add must-gather scripts for sandboxed-containers

---

bundle/manifests/sandboxed-containers-operator.crd.yaml

Use apiextensions.k8s.io/v1 instead of v1beta1, which is not supported anymore. We need to switch to
version v1 or we can't create our own KataConfig CRD anymore. To be clear,
we're updating the version of the CustomResourceDefinition kind, not the version of kataconfig.
See https://github.com/kubernetes/kubernetes/pull/79604

update CRD version to v1

---

controllers/openshift_controller.go

We used to select nodes labelled as workers only. This is wrong
when the user selected a custom label for nodes where the runtime
should be installed. Another case where this doesn't work is on
compact clusters because there we use the master machine config pool.
This can be fixed by using the label that is specified in the
KataConfigPoolSelector.
Remove worker label from nodes so that the worker MCP is empty. Then
create a kataconfig (empty pool selector) and check that the status is updated
during the installation of the runtime.
Correct status update when installing on non-worker nodes (for example nodes labelled differently)
Fixes: #135 …

KATA-1011: update Status of nodes with selected label

---

api/v1/kataconfig_types.go
bundle.Dockerfile
bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
controllers/openshift_controller.go
controllers/openshift_controller_test.go

Fixes: [KATA-918](https://issues.redhat.com/browse/KATA-918)
We have seen cases where users successfully deploy sandboxed-containers operator on cluster nodes but encounter errors when creating Kata containers due to missing capabilities. For example kata containers don’t work on AWS EC2 instances.
Created a new role `kata-oc` (node-role.kubernetes.io/kata-oc) to handle nodes with Kata runtime. Also a new config variable `checkNodeEligibility` is added to KataConfig. If `checkNodeEligibility` is selected, then the operator will look for the node label `feature.node.kubernetes.io/runtime.kata` on the nodes which have the requisite support to run kata containers. 
When `NodeFeatureDiscovery` operator is …

KATA-918: Create NFD as a soft dependency for Sandboxed Containers Operator

---

config/default/kustomization.yaml
config/kata-monitor/kata-monitor-service.yaml
config/kata-monitor/kata-monitor-servicemonitor.yaml
config/kata-monitor/kustomization.yaml
config/rbac/katamonitor.yaml
config/rbac/kustomization.yaml
controllers/openshift_controller.go
controllers/openshift_controller_test.go
main.go

**- Description**
Implements [KATA-1136](https://issues.redhat.com/browse/KATA-1136)
This pull request is meant to make the Operator install everything needed to have kata metrics visible in Prometheus.
This includes:
- a Daemonset, running the kata-monitor binary, to generate kata metrics from each node
- a Service, to expose the kata metrics
- a ServiceMonitor, allowing Prometheus to find the service
- several RBAC rules, allowing prometheus to access all the above
- a label added to our namespace (openshift-sandboxed-containers-operator), so that Prometheus actually looks for the ServiceMonitor in our namespace
- an additional RBAC (to be defined), allowing the operator to create the DaemonSet with privileged status (required to access the socket from shimV2 on the node)
**- What I …

KATA-1136: Metrics prometheus setup

---

controllers/openshift_controller.go

When CheckNodeEligibility is selected, operator unable to find labelled nodes and uses incorrect nodeSelector
for monitor DaemonSet
Fixed the label handling when searching for eligible nodes and used the right nodeSelector
Creating KataConfig and observing the status updates
Fix issues with monitor daemonset and CheckNodeEligibility

Patch series to fix issues with monitor daemonset and CheckNodeEligibility

---

api/v1/kataconfig_types.go
bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml

This series adds additional printer columns to the KataConfig CRD which is displayed in `kubectl get` or `oc get` output.
The improvements are suggested by @zanetworker 
Fixes: #[KATA-1204](https://issues.redhat.com/browse/KATA-1204)
Added relevant kubebuilders markers to include the additional columns.
Create KataConfig and run `oc get kataconfigs.kataconfiguration.openshift.io`
```
NAME                 INPROGRESS   COMPLETED   TOTAL   AGE
example-kataconfig   false        1           1       17m
```
Add additional print columns to KataConfig CRD

Add additional print columns to KataConfig CRD

---

docs/DEVELOPMENT.md

Documentation change - update developer's instructions as an authentication on the registry is now required to build the operator

Add instructions for how to get an authentication token to registry.ci.openshift.org

---

config/kata-monitor/kustomization.yaml
config/kata-monitor/osc-dashboard.yaml
controllers/openshift_controller.go

**What is the use case**
Have the kata-monitor metrics visible as a graph under the "Dashboard" section of OpenShift
The content of the dashboard is defined as a ConfigMap, under the operator's
namespace.
When kataconfig is deployed, this ConfigMap is copied and installed under
the appropriate namespace (openshift-config-managed).
The resulting dashboard is accessible under the "Observe/Dashboard" section
in the OpenShift console.
Install the operator, and deploy kataconfig as usual.
Once correctly setup, open the web console, move to "Observe/Dashboard".
Open the "Dashboard" dropdown field at the top. A new dashboard must be available, named "Sandboxed Containers".
This Dashboard shows simple graphs on the pods running with sandboxed containers.

KATA-1145: Introduce metrics dashboard in OCP console.

---

controllers/openshift_controller.go

We don't update the node selector in the machine config pool
object when a user changes the selector in the KataConfig CR spec.
What we should do is to make sure that in every reconcile 
the specified node selector matches what we set in the machine
config pool. With this fixed the users settings are applied
to the cluster.
1. label a node with custom-kata=test
2.  create a kataconfig with a node selector kata=test (it shouldn't match the label of the node in step 1)
3. verify that the kata-oc pool is empty
4. edit the kataconfig and set the node selector to kata=test (so that it matches the label from step 1)
5. open the log and check that you see a message "Updating machine …

KATA-1190: always update mcp during reconcile

---

api/v1/kataconfig_types.go
bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml

The current description of the "CheckNodeEligibility" option that is displayed when creating KataConfig via OpenShift UI is misleading.
Updated the description to closely aligned with the implementation
When creating the KataConfig instance, check the description of the "CheckNodeEligibility" option and you should see the following:
```
"CheckNodeEligibility is used to detect the node(s) eligibility to run Kata containers. 
This is currently done through the use of the Node Feature Discovery Operator (NFD). 
For more information on how the check works, please refer to the sandboxed containers documentation - https://docs.openshift.com/container-platform/latest/sandboxed_containers/d …
```

Update description of CheckNodeEligibility option

---

controllers/scc.go

To make the daemonset that runs kata-metrics unprivileged
we change the SELinux type to a custom policy that is installed
via the kata-containers rpm.
See https://issues.redhat.com/browse/KATA-1189 for more information
on the new policy.
Fixes: https://issues.redhat.com/browse/KATA-1200

KATA-1200: use osc_monitor policy for metrics daemonset

---

controllers/openshift_controller.go

For a kataconfig where spec.kataConfigPoolSelector is nil we would run into this error.
A check before assigning something to it prevents the segfault. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x173baaf]
goroutine 613 [running]:
github.com/openshift/sandboxed-containers-operator/controllers.(*KataConfigOpenShiftReconciler).processKataConfigInstallRequest(0xc00063c200, 0x13ac965, 0xc000010860, 0x1d8d5c8, 0xc000044138)
/home/jfreiman/go/src/github.com/openshift/kata-operator/controllers/openshift_controller.go:779 +0x6cf
github.com/openshift/sandboxed-containers-operator/controllers.(*KataConfigOpenShiftReconciler).Reconcile.func1(0xc00063c200, 0x1d8d5c8, 0xc000044138, 0x0, 0x0) …

KATA-1289: use deepcopy to update node selector

---

controllers/openshift_controller.go

We don't update the node selector in the machine config pool
object when a user changes the selector in the KataConfig CR spec.
What we should do is to make sure in every reconcile that
the specified node selector matches what we set in the machine
config pool. With this fixed the users settings are applied
to the cluster.

backport release-1.2: KATA-1190: always update mcp during reconcile

---

controllers/openshift_controller.go

changes to spec.kataMonitorImage had no effect. This fixes it and
applies whatever is in the spec to the osc-monitor daemon set.
Fixes: https://issues.redhat.com/browse/KATA-1288

KATA-1288: update kataMonitorImage during reconcile

---

api/v1/kataconfig_types.go
bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
config/rbac/role.yaml
controllers/openshift_controller.go

To debug some kinds of problems with kata-enabled workers it's helpful
or even necessary to make CRI-O on the workers log in debug mode.  So
far, this was in principle achievable by a user but some knowledge of
internals of Sandboxed Containers Operator and OpenShift itself was
required.
This commit introduces a new 'logLevel' field in KataConfig.spec which
can be used to set easily a corresponding log level on nodes.
Internally, it works by creating or updating a ContainerRuntimeConfig
instance which requests MCO to set the desired log level on relevant
nodes.  The relevant nodes are all masters (more specifically, all
members of the master Machine Config Pool) in case of a converged
cluster, or nodes defined by the OSC-internal 'kata-oc' MCP otherwise.
To support this implentation, this …

enable changing CRI-O log level on kata workers by changing KataConfig

---

controllers/openshift_controller.go

[KATA-1340](https://issues.redhat.com/browse/KATA-1340): allow re-install on all workers
When we first install with KataConfigPoolSelector set on specific nodes
and later on remove that selector from kataconfig, re-installation on
all worker nodes is never going to happen.
The reason is that the kata-oc machine config pool is never updated
correctly, the old matchLabel key-value pair is never removed.
This patch fixes the problem by adding all matchLabel entries when
kataConfigPoolSelector is non-empty in every reconcile run.  When the
selector is deleted from kataconfig we create a new kata-oc machine
config pool with only our default matchLabels for the worker and kata-oc
role set. The kata-oc entry is required because we always create this
role even when we install on all worker nodes. …

KATA-1340: allow re-install on all workers

---

controllers/openshift_controller.go

When we first install with KataConfigPoolSelector set on specific nodes
and later on remove that selector from kataconfig, re-installation on
all worker nodes is never going to happen.
The reason is that the kata-oc machine config pool is never updated
correctly, the old matchLabel key-value pair is never removed.
This patch fixes the problem by adding all matchLabel entries when
kataConfigPoolSelector is non-empty in every reconcile run.  When the
selector is deleted from kataconfig we create a new kata-oc machine
config pool with only our default matchLabels for the worker and kata-oc
role set. The kata-oc entry is required because we always create this
role even when we install on all worker nodes.
The deletetion-and-reinstall also works when a matchExpression is used
in kataconfig …

 KATA-1340: allow re-install on all workers

---

bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Currently we restrict the operator to run on master nodes only.
However, there is no technical reason for this setting. It
creates a problem when a cluster-admin sets the defaultNodeScheduler
field to schedule everything to workers. In that case our controller
could not be placed anywhere by the scheduler and would get stuck
in 'Pending' state.
By removing the nodeSelector field from our controller manifest we let
the scheduler place the controller pod also on worker nodes so that we
don't get into the above described situation anymore.
I tested this on clusters with
- three control-plane and three worker nodes
- a converged cluster where control-plane and worker nodes are on the
same machines
- a single-node cluster
and did not run into problems. The test procedure included deploying a …

KATA-1444: remove nodeSelector from controller deployment

---

must-gather/collection-scripts/gather_nodes

The version information is collected separately from individual nodes and
stored at the root of each node's respective subtree of must-gather output.

KATA-1321: add versions of kata and qemu to must-gather output

---

controllers/openshift_controller.go

In the upstream kata-containers repo the kata-monitor binary is now
listening on the loopback address by default:
https://github.com/kata-containers/kata-containers/commit/e64c54a2ad7
Since the DaemonSet needs to expose the endpoint to Prometheus, let's
specify the "listen-address" argument.
This will cause no changes with older/current kata-monitor images but
will allow to switch seamlessy to the latest kata-monitor images
preserving the availability of the endpoint to Prometheus.

kata-monitor DaemonSet: add the "listen-address" arg

---

docs/DEVELOPMENT.md

Assorted fixes, especially:
- tell how to install operator-sdk
- add 'make bundle' in the list of steps, otherwise you end up pushing
a broken bundle image

Improve developer documentation

---

main.go

Fixes: #[KATA-1583](https://issues.redhat.com//browse/KATA-1583)
OpenShift 4.11 is going to enable pod security admission (https://kubernetes.io/docs/concepts/security/pod-security-admission/) using the “restricted” profile by default (https://kubernetes.io/docs/concepts/security/pod-security-standards/) 
Since we require privileged support for kata-monitor, we need to label the namespace accordingly
Added required labels to the `openshift-sandboxed-containers-operator` ns
Create a Kata Pod and check controller logs for `pod-security.kubernetes.io/audit-violations`.
There shouldn't be any audit-violations when kata-monitor pods gets created
Add …

Add namespace label to align with Pod Security Admission requirements

---

controllers/openshift_controller.go

This is a cleanup patch to rename method name to better reflect the functionality. Additionally only returning error.

Rename setRuntimeClass to createRuntimeClass and change return values

---

controllers/openshift_controller.go

The recently introduced `createScc()` is missing an error path. Same issue exists in `createRuntimeClass()`. Fix both.

Fix some error paths in the controller

---

controllers/openshift_controller.go
controllers/scc.go
main.go

This brings the fix of PR #196 to the 1.2 release, along with an extra patch to an already created SCC.
This will simplify OCP upgrades.

Fix SCC in OSC 1.2

---

controllers/openshift_controller.go

Add the "pools.operator.machineconfiguration.openshift.io/kata-oc" label
to an existing pre-1.3 MCP. This is needed to control the crio log level
through KataConfig.spec.logLevel.
Fixes: [KATA-1653](https://issues.redhat.com//browse/KATA-1653)

Fix 1.2-style MCP

---

api/v1/kataconfig_types.go
config/manager/manager.yaml
controllers/openshift_controller.go
controllers/openshift_controller_test.go
controllers/suite_test.go

This PR removes spec.kataMonitorImage from the KataConfig CR.  kata-monitor container image URL is basically a technical implementation detail of OSC and as such has no good place in KataConfig.
The OSC controller now gets the kata-monitor image URL from an environment variable KATA_MONITOR_IMAGE instead of a KataConfig instance.  The default value is now part of the manager container template in OSC controller-manager Deployment.

Remove kata monitor image

---

config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml

OCP 4.12 is now enforcing the "restricted" Pod Security Admission (PSA) policy by default for every pod. This includes the pods that belong to the operator, i.e. the controller manager and the monitors. As a consequence, subscribing to OSC currently fails with the following error:
message: 'pods "controller-manager-6dff96dbb8-m2twk" is forbidden: violates
PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container
"manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted
capabilities (container "manager" must set securityContext.capabilities.drop=["ALL"]),
runAsNonRoot != true (pod or container "manager" must set securityContext.runAsNonRoot=true),
seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type
to …

Add security contexts to the operator

---

Makefile

This provides a finer grained way to prune generated files from the current tree over calling `git clean`. Each target that generates files gets an associated `${target}-clean` : this provides a clear view of which target generates what. Only exceptions are downloaded binaries which all get pruned by a single `bin-clean` target for the sake of simplicity.

Add cleanup rules to Makefile

---

OWNERS

Greg has been reviewing and contributing to the operator or a while, let's add him to OWNERS.

Add gkurz to OWNERS

---

Dockerfile

Older versions of OCP are unhappy with the non-numeric ids and the controller fails to start with the following error:
container has runAsNonRoot and image has non-numeric user (nonroot),
cannot verify user is non-root
The nonroot stuff was generated by an old operator sdk. Recent versions now put numerical ids. Do the same.
Fixes: https://issues.redhat.com/browse/KATA-1824
Fixes: rhjira#[KATA-1824](https://issues.redhat.com//browse/KATA-1824)

Use numerical uid/gid in Dockerfile

---

.dockerignore
Makefile

When building manually (using make targets and setting env vars) the output is a bundle that still points to the production image for the operator.  This is because the bundle-build uses the bundle-custom.Dockerfile which has the production values hard coded.
Change the bundle-build target back to using the generated bundle.Dockerfile so it respects set env vars and includes the respective operator image.  Also had to remove "bundle" from .dockerignore so that the docker build can succeed.
make bundle-build
install the operator using that bundle
Verify it is using the expected operator image for the controller pods
Closes: https://issues.redhat.com/browse/KATA-1828

use generated bundle.dockerfile; remove bundle from .dockerignore

---

Makefile
bundle-custom.Dockerfile
config/manager/kustomization.yaml

Default values should represent upstream builds and allow custom builds with vars
Closes: [KATA-1838](https://issues.redhat.com//browse/KATA-1838)
Changed image repos to quay.io so that a running make targets will generate something accessible upstream
build with make targets by not setting any variables
build with make targets setting a custom IMAGE_TAG_BASE

make upstream values default

---

OWNERS

Add @cpmeadors as reviewer and approver

Update OWNERS, add cpmeadors

---

README.md

After we renamed the branch, let's also change it in the README 
I didn't change .travis.yml because it's not used any more and we should get rid of it in a separate PR.

README: s/master/main/

---

go.mod
go.sum

Our downstream build process of the operator image has not network access so we need to use the go module caching feature to run controller-gen directly rather than downloading the binary
Required for [KATA-1800](https://issues.redhat.com//browse/KATA-1800)
`$ go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0`
` $ go mod download`
` $ go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."`
THis should generate the same files as running make generate does.

Add controller-tools to go.mod for downstream build

---

Makefile
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

This sets VERSION in the Makefile to 1.3.2.
It also updates the csv version and skipRange in config/manifests/base because we don't generate that part of the CSV yet and have to update it manually.

set version to 1.3.2

---

bundle-custom.Dockerfile
docs/DEVELOPMENT.md

Following steps from https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.24.0/
No change required for go-based operators.
Just modified the bundle-custom.Dockerfile and developer's doc to reference the newer SDK.

Upgrade to operator-sdk v1.24

---

config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

This was removed earlier but needs to be added back in order to pass validation.
Fixes rhjira:[KATA-1876](https://issues.redhat.com//browse/KATA-1876)
Please provide the following information:
This annotation was removed by accident. It is required to show users which subscription of OCP is required and also to pass a validation test downstream
add the annotation to the CSV
The CVP tests should pass and it should also be displayed in Operatorhub

manifests: add back valid-subscription annotation

---

config/manager/manager.yaml

It is used by the peer-pod-controller, so let's set it in the controller-manager deployment.

add PEERPODS_NAMESPACE variable to controller-manager deployment

---

config/peerpods/mc-50-crio-config.yaml

The peer-pod crio config didn't include "privileged_without_host_devices = true" setting resulting in failure of privileged containers
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>

Update MachineConfig to include privileged_without_host_devices setting

---

Makefile

If one calls make bundle-build without a make bundle beforehand, it will error out:
```
$ make bundle-build
docker build -f bundle.Dockerfile -t openshift-sandboxed-containers-operator-bundle:v1.3.2 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat sandboxed-containers-operator/bundle.Dockerfile: no such file or directory
```
Added `bundle` as dependency of `bundle-build`
Run `make bundle-build` without calling `make bundle` beforehand.
Makefile: Target bundle-build requires bundle

Makefile: Target bundle-build requires bundle

---

OWNERS

Let's add @littlejawa as reviewer and committer

Update Owners, add @littlejawa

---

main.go

Timestamps are currently displayed as number of seconds since the Epoch using scientific notation, i.e. 1.6759526089944808e+09.
This is definitely not human friendly. Newer versions of the zap package now render timestamps according to RFC3339, i.e. 2023-02-09T14:38:20Z.
We're not ready to bump the controller-runtime package that brings us zap. Let's configure zap to explicitly use RFC3339.

Encode log timestamps as RFC3339

---

Makefile
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

In preparation for the next release, set version in Makefile and the CSV to 1.4.0. Not having to touch the CSV manually is still a todo that we're working on, at the moment it is still required though.

set version to 1.4.0

---

docs/DEVELOPMENT.md

The instructions for downloading the operator SDK was updated from operator SDK home page.
Fixes #263 
Updated the instructions.
Follow the instructions. Notice that the file now is more than 0 bytes and also is an executable.
Nope. I don't think this should be inserted into the changelog.

Update operator SDK instructions.

---

controllers/openshift_controller.go
controllers/osrelease.go
controllers/osrelease_test.go
go.mod
go.sum
main.go

The machine config operator handles RHCOS and FCOS differently when effectuating machine config extensions.
On RHCOS it uses a hardcoded list which is then translated into the actual packages. In our case, `sandboxed-containers` are translated into `kata-containers` and then rpm-ostree is called.
On FCOS it just pipes the extensions directly into rpm-ostree, which means that in the current implementation it tries to install `sandboxed-containers` which doesn't exist in FCOS yum repo.
Fixes #267 
I added an OS detection mechanism and if it's RHCOS I use `sandboxed-containers` as extension, otherwise I use `kata-containers`. 
In theory it's unfortunate that it's the OS of the operator that I use for …

Setup os dependent machine config extensions.

---

controllers/openshift_controller.go

This PR aims to fix a long-standing problem where `kataConfigPoolSelector` allows users to use `MatchExpressions` but then the controller code handling the selector cannot process the `MatchExpressions` part and ends up effectively ignoring it.
Please check out the initial commit's message for a detailed explanation of the problem and the fix.
Fixes: [KATA-1860](https://issues.redhat.com//browse/KATA-1860)
Fixes: [KATA-1966](https://issues.redhat.com//browse/KATA-1966)
Closes: [KATA-1965](https://issues.redhat.com//browse/KATA-1965)

Fix kata node selector handling

---

controllers/openshift_controller.go

This PR fixes problems in kata node selector handling introduced by recent changes.  They include
- an empty kata node selector can be represented by nil as opposed to an empty `metav1.LabelSelector` instance
- nil and empty LabelSelector selectors are allowed but handled radically differently by apimachinery (an empty instance matches everything, nil matches nothing)
- default k8s syntax checking of `matchExpressions` doesn't catch invalid `matchExpressions.operator` values.

Fix corner case node selector handling

---

controllers/openshift_controller.go

In commit 7dae22183ecfa781c5fb50e4017a337d577bac78 and df06ae971b52df90e336457cd489788a9463f6b4 I turned '250m' into '250M'. This means a pod will request 250 full CPUs instead of a quarter CPU.
Fixes: rhjira#[KATA-2069](https://issues.redhat.com//browse/KATA-2069)

controller: fix wrong amout of cpu request in RuntimeClass

---

PROJECT
config/manifests/extension-crds/confidentialcontainers.org_peerpodconfigs.yaml
config/manifests/extension-crds/kustomization.yaml
config/manifests/kustomization.yaml

We need the PeerPodConfig CRD file in the bundle so that it is deployed with the Operator.
add the peerpodconfig crd to the PROJECTS file, so that it's included as an owned resource in the CSV and add
the full CRD yaml file to config/manifests/extension-crds/
Deploy the operator and check the controller log, if there is no error message saying that it can't find
the peerpodconfig CRD, then the problem is fixed.
Fixes: rhjira#[KATA-2098](https://issues.redhat.com//browse/KATA-2098)

bundle: add peerpodconfig crd file

---

controllers/openshift_controller.go
controllers/openshift_controller_test.go

When PeerPods is enabled checkNodeEligibility should not take into consideration since PeerPods doesn’t require KVM/qemu.
I'm checking if enablePeerPods is enabled during checkNodeEligibility().
Enable both checkNodeEligibility and enablePeerPods in you kata-config and check controller logs.
Configuration: Ignoring checkNodeEligibility when peer pods is enabled.

controller: checkNodeEligibility vs peerpods: noop

---

controllers/openshift_controller.go

Most target in the makefile, e.g. 'make test' or 'make build', internally invoke 'make fmt' which reformats all the go code.
Despite of that, badly formatted go code landed in the repo. This causes unrelated changes to appear in local repos during regular development. This is quite irritating for picky(?) people who don't want to push alien changes in their PRs.
A long term solution would be that the gating CI catches those nits upfront. They are a variety of solutions available to developers to run 'go fmt' in their environement before pushing changes.
In the meantime, fix the current code base. This obviously doesn't change any behavior.
No testing required.

Reformat go code

---

Dockerfile
Makefile
docs/DEVELOPMENT.md

Current build assumes the developer is a RH employee and uses images not publicly available.
Closes #268 
- Updated Dockerfile to take images as arguments
- Updated current make target to include (the same) images as arguments when building docker images.
- Added documentation about building docker images from public images.
Build with existing make targets:
```
make docker-build
make docker-buildx
```
Build with public images:
```
export BUILDER_IMAGE=registry.ci.openshift.org/openshift/release:golang-1.18
export TARGET_IMAGE=registry.ci.openshift.org/origin/4.10:base
make docker-build
make docker-buildx
```
Added support for overriding images …

Optionally use public images

---

Makefile
go.mod
go.sum
main.go

This is to ensure that the modules are in go.mod and hence can be cached by downstream builds.  This also ensures that running `go mod tidy` will not remove these modules as these are not used in the code. This improves upon the PR-294 fix as it was an incomplete fix and didn't include all the required deps.

Add unused references to go modules in the import section.

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go

This PR reworks the installation flow with two main objectives in mind: rearrange major steps (e.g. MC and MCP creation) so that they follow the most straightforward and natural succession possible, and remove arbitrary waits throughout the procedure, replacing them with a small number of better-founded ones.
A number of smaller clean-ups are also done in the initial commits of this series.
Fixes: [KATA-1969](https://issues.redhat.com//browse/KATA-1969)
Fixes: [KATA-2143](https://issues.redhat.com//browse/KATA-2143)

Improve installation steps

---

Dockerfile
Makefile
docs/DEVELOPMENT.md

The base golang and target container images were old and not in sync with code requirements
Replaced with the 4.13 base images
"make docker-build" will pull the latest images
Update the base container images to align with 4.13 images

Update the base container images to align with 4.13 images

---

controllers/openshift_controller.go

```   
controller: fix incorrect logs in createAuthJsonSecret
If the client is just updated with no error, the code was always falling
back to r.Log.Info("Error creating auth-json-secret", "err", err)
thus printing it also when it was not necessary.
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
```

controller: fix incorrect logs in createAuthJsonSecret

---

controllers/openshift_controller.go

The peerpods config enablement is split into two parts - one part deals with creation of MachineConfigs before "kata-oc" MCP creation and another part deals with creation of PeerPodConfig CRD, runtimeclass and other misc configs after "kata-oc" MCP has updated.
The reason for this split is to ensure that MachineConfigs are created before "kata-oc" creation so as to optimise the number of reboots required when applying MachineConfigs. Further, the relevant node labels are only available when "kata-oc" MCP is updated, thereby making it available for the creation of PeerPodConfig CRD
The cloud-api-adaptor daemonset was not taking into account the KataConfigPoolSelector
Fixes: …

Ensure KataConfigPoolSelector is used for PeerPodConfig CRD

---

controllers/openshift_controller.go

This PR is an uninstallation couterpart of PR #291.  The core of the change is migrating uninstallation to the exact same flow logic that installation has benefited from with a side benefit of a consistent idea behind both.
Apart from the tracked issues listed below, this PR also fixes a leakage of `logLevel` ContainerRuntimeConfig resource and removes spurious error messages at the end of each uninstallation that have been confusing people routinely.
Fixes: [KATA-2139](https://issues.redhat.com//browse/KATA-2139)
Fixes: [KATA-1926](https://issues.redhat.com//browse/KATA-1926)
Fixes: [KATA-1972](https://issues.redhat.com//browse/KATA-1972)

Improve uninstallation flow

---

controllers/suite_test.go

`make test` is leaking the kube-apiserver and etcd processes. When unoticed, this causes `make test` to fail with weird errors like failing to open a file because of rlimit.
Investigation leads to commit 053f8664bf29d which was added to work around the very same problems at the time according to Pradipta. Reverting this commit fixes the issue.
It seems that updates to the controller-runtime and deps might have changed something and we no longer need the workaround.
Let's just revert 053f8664bf29d.
Fixes https://issues.redhat.com/browse/KATA-2168

Revert "Fix errors during envtest teardown"

---

go.mod
go.sum

Fixes divide by zero error when running the peerpodconfig controller
Closes: #[KATA-2165](https://issues.redhat.com//browse/KATA-2165)
Bumped up the deps to pull the upstream fix for the issue
Edit peerpodconfig CRD and use a non-existent label in NodeSelector. This should not crash the controller-manager.
Fix "divide by zero" error when running peerpodconfig controller

Bump up peerpod-ctrl and peerpodconfig-ctrl deps

---

hack/aws-image-job.yaml
hack/azure-image-job.yaml

apply scripts to create image in AWS/Azure

add image creation jobs for aws and azure

---

config/manager/manager.yaml
controllers/openshift_controller.go
controllers/suite_test.go
go.mod
go.sum

Add the cloud-api-adaptor(-webhook) image as a relatedImage to the CSV.
Fixes: rhjira#[KATA-2159](https://issues.redhat.com//browse/KATA-2159)
add cloud-api-adaptor images as related images. By adding them to config/manager/manager.yaml they will be automatically added to the generated CSV when `make bundle` is run. 
Add the caa and caa-webhook image to the manager.yaml file. This is related to and dependent on  https://github.com/confidential-containers/cloud-api-adaptor/pull/963 which changes the env variable name
the generated CSV includes the env vars RELATED_IMAGE_CAA(_WEBHOOK). When built with OSBS and digest pinning is enabled it should replace the tag in the pull spec with …

KATA-2159: add cloud-api-adaptor images as relatedImage

---

config/manager/manager.yaml
controllers/openshift_controller.go
controllers/ppwebhook.go

Fixes: #[KATA-2172](https://issues.redhat.com//browse/KATA-2172)
peer pods resource management relies on a mutating webhook to add the extended resources to the pod spec.
Added mutating webhook installation to the controller
1. Create a pod using `kata-remote-cc` runtimeclass
2. Verify the pod spec to check if the following is added
```
resources:
limits:
kata.peerpods.io/vm: "1"
requests:
kata.peerpods.io/vm: "1"
```
Install mutating webhook for peerpods

Install peerpods mutating webhook

---

Makefile

`make test` has been broken since #300 was merged and fixing it is going to take time (see #310 for details). It is a problem for local development since the `test` target is a prequisite for `docker-build` in the makefile.
Add a variable to control whether `go test` should run when the `test` target is invoked.
$ make test SKIP_TESTS=   # Run `go test` when unset
$ make test SKIP_TESTS=1  # Don't run `go test` when set
Default is unset. [edit]

Allow to skip `go test`

---

config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

based on:
https://docs.openshift.com/container-platform/4.12/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs

hide peerpods and peerpodconfigs internal objects

---

hack/aws-image-job.yaml
hack/azure-image-job.yaml

image-job: fix payload url

---

controllers/openshift_controller.go

No metrics for sandboxed containers running on a tainted node.
Allow monitor pods to tolerate all taints.
1. Install OSC.
2. Taint worker nodes.
3. Create KataConfig.
4. Monitor pods should be running on all nodes in the kata-oc MCP.
The DaemonSet launched by the controller doesn't put tolerations on the monitor pods. This prevents the monitor pods to run on tainted nodes and break metrics for sandboxed containers.
The monitor pods must run on every node where kata is deployed, no matter any taint the user might have set. Enforce a toleration that matches all possible taints.
Fixes https://issues.redhat.com/browse/KATA-2121

Allow monitor pods to run on tainted nodes

---

controllers/openshift_controller.go

This PR aims to fix KataConfig.status updating to handle installation modifications (adding and removing kata-enabled Nodes) to the extent I believe possible without changing the KataConfig.status structure itself.
Some not so intuitive aspects of the result, apart from names dictated by the current form of KataConfig.status, include:
- *all* Done Nodes will appear on one of the Completed lists, not just the ones affected by the ongoing or most recent operation.  This is because I'm not aware of any way of telling apart Nodes that had arrived in their state earlier as opposed to as a result of the most recent operation.
- Nodes scheduled to change state (=install/uninstall kata) as part of an ongoing operation but still waiting to do so are not listed anywhere since there doesn't seem to …

Fix kataconfig status handling to support installation updates

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go

This PR adds a new section to `KataConfig.status`  called `kataNodes` which lists cluster nodes grouped by the status of kata installation on them which can be one of installed, installing, waiting to install, failed to install, not installed, uninstalling, waiting to uninstall and failed to uninstall.
By way of example, when applying a KataConfig that selects both nodes of a two-worker cluster, the newly added section might show
```
kataNodes:
waitingToInstall:
- worker-0
- worker-1
```
for a brief period of time, then something like
```
kataNodes:
installing:
- worker-1
waitingToInstall:
- worker-0
```
Once `worker-1` is installed the other worker starts installing
```
kataNodes:
installed:
- worker-1
installing:
- worker-0
```
and finally
```
kataNodes:
installed:
- worker-0
- worker-1 …
```

New way of showing kata nodes in kataconfig status

---

controllers/openshift_controller.go

This applies selected fixes from the devel branch to main for the 1.4.1 release :
- 7f004df4303e Allow monitor pods to run on tainted nodes ([KATA-2121](https://issues.redhat.com/browse/KATA-2121))

Fixes for 1.4.1

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go

This PR adds a conventional Kubernetes Condition type and a Condition array to KataConfig.status.  The only Condition currently supported is InProgress with three possible Reasons - Installing, Updating and Uninstalling.
The final commit doesn't really fit here since it fixes an omission in #329 but I included it anyway since it's a tiny change that probably wouldn't be worth a separate PR IMHO.
With this PR I believe all is set to remove the legacy parts of KataConfig.status.  Anybody depending on them is encouraged to migrate to the new KataConfig.status structure.
As a migration guide, note that
- `installationStatus.IsInProgress == True` should correspond to `InProgress.status == True` and `InProgress.reason` either `Installing` or `Updating`
- `unInstallationStatus.inProgress.status …

Switch to condition for progress status reporting

---

config/manager/kustomization.yaml
config/samples/deploy.yaml

Despite 1.4.0 was released about a month ago, there are still some mentions of 1.3.x in the tree :
$ git grep -e '1\.3\.[0123]' -- ':!go.*'
config/manager/kustomization.yaml:  newTag: 1.3.1
config/samples/deploy.yaml: image:  quay.io/openshift_sandboxed_containers/openshift-sandboxed-containers-operator-catalog:v1.3.0 config/samples/deploy.yaml:  startingCSV: sandboxed-containers-operator.v1.3.0
This is essentially because we don't do automated upstream builds.
Let's bump the versions to latest public release : 1.4.0.
Fixes https://issues.redhat.com/browse/KATA-2245

Bump outdated versions of OSC components

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go
controllers/openshift_controller_test.go

This PR removes parts of `KataConfig.status` obsoleted by #330 (and #329 before it), `totalNodesCount`, `installationStatus`, `unInstallationStatus` (and the stub of `upgradeStatus`).

Remove legacy kata config status parts

---

controllers/openshift_controller.go

When you try to delete kataconfig while a workload is running, you will get an error that kataconfig cannot be deleted while it is running a workload.
You should be able to delete the workload and kataconfig will remove the status and will proceed to delete kataconfig.  This is the previous 1.3.3 behavior.
Fixes: https://issues.redhat.com/browse/KATA-2240
Cherry-picked all patches from #327 
1. build OSC from this PR
2. deploy it on OCP 4.13.x
3. create kataconfig with  enablePeerPods: false
4. create a sandboxed pod workload
6. delete kataconfig
7. see the expected `Existing pods using Kata Runtime found. Please delete the pods manually for KataConfig deletion to proceed` error in …

Fix kataconfig status handling to support installation updates (port to main)

---

hack/azure-image-job.yaml

The LVM based image results in limited free space for the root filesystem. This creates issues when using peer-pods for container builds. Switching to raw images provides flexibility w.r.to root filesystem storage
Fixes: [KATA-2362](https://issues.redhat.com//browse/KATA-2362)

Use raw Azure base image for peer-pods

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go

This controller can now create multiple RuntimeClasses, for plain kata
and for peer pods.  However only the original kata RuntimeClass has ever
been accounted for in KataConfig.status.runtimeClass so far.
This is not merely a cosmetic problem.  The controller uses
KataConfig.status.runtimeClass to find out whether there are any pods
using the kata runtime before it removes the runtime from a cluster on
uninstallation.  Since the peer pods RuntimeClass was never represented
in the field so far, running peer pods were ignored on uninstallation.
As for implementation, KataConfig.status.runtimeClass is now optional,
not required.  This doesn't really have to do with the core idea of this
commit, it's more to work around the fact that kubebuilder doesn't seem
to support array fields with an …

Support multiple runtimeclasses in kataconfig.status.runtimeClass

---

controllers/openshift_controller.go

A chunk was unfortunately left out from PR #344 by mistake.
We also take this opportunity to split the condition in the daemonset creation error checking to get rid of a long-standing logging annoyance. No error should be logged if getting the DS returns "not found".

PR #344 fixup

---

config/manager/manager.yaml
config/peerpods/podvm/aws-VM-image-create-job.yaml
config/peerpods/podvm/aws-VM-image-delete-job.yaml
config/peerpods/podvm/azure-VM-image-create-job.yaml
config/peerpods/podvm/azure-VM-image-delete-job.yaml
controllers/image_generator.go
controllers/openshift_controller.go
controllers/utils.go
main.go

EDITED:
This PR contains several features:
1. **AWS**: if image is not specified it will generate AMI image and update the CM with it when KataConfig is created (and it will be deleted when KataConfig is deleted)
2.  **Azure**: if image is not specified it will generate Azure image and update the CM with it when KataConfig is created (and it will be deleted when KataConfig is deleted)
3. **Azure&AWS**: if cluster is installed with **fips=true** all created images will boot with kernel cmdline parameter fips=1
To test use:
```
quay.io/snir/osc-operator:v1.4.8
quay.io/snir/osc-operator-bundle:v1.4.8
quay.io/snir/osc-operator-catalog:v1.4.8
```

podvm: run image jobs from the controller automatically

---

Makefile
config/manager/kustomization.yaml
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
config/samples/deploy.yaml
hack/aws-image-job.yaml
hack/azure-image-job.yaml

As a preparatory step for the upcoming release, this bumps the version to 1.5.0 in Makefile, the CSV and images.
Note that the updated images aren't available at this stage. They will be added later. Until then the image links aren't valid.

Bump OSC to 1.5.0

---

Makefile
controllers/openshift_controller.go

It seems to me the right approach, cc @gkurz @pmores @bpradipt for confirmation this is legit

makefile: match operator, bundle and catalog versioning

---

controllers/image_generator.go

this allows installtion completion without being blocked waiting
for image creation when image creation isn't implemented for
cloud-provider

image-generator: skip image creation for unsupported providers

---

api/v1/kataconfig_types.go
controllers/openshift_controller.go

This fixes [KATA-2593 (Kata Operator upgrade failed 1.4.1 to 1.5.0)](https://issues.redhat.com/browse/KATA-2593) .
Renamed the offending field in KataConfigStatus and improved idempotency of the controller.
1. Install OSC 1.4.1 with automatic upgrade enabled [use catalog image at *]
2. Create a KataConfig
3. Setup a catalog source with this PR [use catalog image at **]
4. Patch the subscription of the operator to select the new source
```
oc patch subscription -n openshift-sandboxed-containers-operator sandboxed-containers-operator -p '{"spec":{"source":"my-operator-catalog", "startingCSV":"sandboxed-containers-operator.v1.5.1", "channel":"candidate"}}' --type merge
```
5. Upgrade …

Fix upgrade from OSC 1.4.1

---

must-gather/collection-scripts/gather_nodes
must-gather/must-gather-requirements.md

https://issues.redhat.com/browse/KATA-815 Document must-gather image [developer / support facing] 
Creates must-gather/must-gather-requirements.md

KATA-815 Document must-gather for developers

---

config/peerpods/podvm/aws-VM-image-create-job.yaml
config/peerpods/podvm/aws-VM-image-delete-job.yaml
config/peerpods/podvm/azure-VM-image-create-job.yaml
config/peerpods/podvm/azure-VM-image-delete-job.yaml

* at creation: name images with unique naming to aviod name reuse failures
* at deletion: ignore if image is already deleted
Fixes: #[KATA-2618](https://issues.redhat.com//browse/KATA-2618)
to test:
```
quay.io/snir/osc-operator:v9.9.2618
quay.io/snir/osc-operator-catalog:v9.9.2618
quay.io/snir/osc-operator-bundle:v9.9.2618
```
in OCP make sure to set also:
`oc set env deployment.apps/controller-manager SANDBOXED_CONTAINERS_EXTENSION=sandboxed-containers -n openshift-sandboxed-containers-operator`

image-generator: fix image creation edge cases

---

Makefile
config/manager/kustomization.yaml
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
config/samples/deploy.yaml
hack/aws-image-job.yaml
hack/azure-image-job.yaml

As a preparatory step for the upcoming release, this bumps the version to 1.5.2 in Makefile, the CSV and images.
Note that the updated images aren't available at this stage. They will be added later. Until then the image links aren't valid.

Bump OSC to 1.5.2

---

config/peerpods/podvm/Dockerfile
config/peerpods/podvm/podvm-builder.sh

Downstream builds can't use binaries. So move the binaries out of the Dockerfile
Related to #[KATA-2821](https://issues.redhat.com//browse/KATA-2821)

Adapt the scripts and Dockerfile for downstream builds

---

config/peerpods/podvm/Dockerfile
config/peerpods/podvm/osc-podvm-create-job.yaml

This avoids duplication and enables independent dev of both the container images required for building podvm image

Avoid copying payload binaries to the builder image

---

Makefile
config/manager/kustomization.yaml
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
config/samples/deploy.yaml
hack/aws-image-job.yaml
hack/azure-image-job.yaml

Prepare the release of OSC 1.5.3 on the main branch. A subsequent PR will be created to merge this change back into the devel branch.
Fixes: [KATA-2876](https://issues.redhat.com//browse/KATA-2876)

Bump OSC to 1.5.3

---

config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

CVP downstream requires new annotations to exist in the CSV. https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
Closes: [KATA-2881](https://issues.redhat.com//browse/KATA-2881)
Added the annotations to CSV.  I set disconnected to true and all the rest false.  We can update them if that is wrong, but this should satisfy CVP.
Make bundle.  Check bundle/manifests/sandboxed-containers-operator.clusterserviceversion.yaml to see if new annotations are in rendered CSV

KATA-2881: add new annotations to CSV

---

config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml

This is now mandated by CVP if the CSV uses the `skipRange` field.

Introduce `replaces` field in CSV

---

Makefile
config/manager/kustomization.yaml
config/manifests/bases/sandboxed-containers-operator.clusterserviceversion.yaml
config/samples/deploy.yaml
hack/aws-image-job.yaml
hack/azure-image-job.yaml

This reverts commit c6bedbaba26a65f7fb25320ec23b9c86ddc23f13, reversing changes made to e2b13745ee3e160007fac019b058a543ae9bf748.
This brings devel back to a sane state, predating the tentatives to merge 1.5.3 related changes.
Fixes: [KATA-2876](https://issues.redhat.com//browse/KATA-2876)
`git revert -s -m 1 c6bedbaba26a65f7fb25320ec23b9c86ddc23f13`
- checkout this PR locally
- No output expected with `git diff e2b13745ee3e160007fac019b058a543ae9bf748`

Mass revert 1.5.3 devel

---

Dockerfile
Makefile
docs/DEVELOPMENT.md
go.mod
go.sum

Bump golang version to 1.21
